add_lunch_combo xenonhd_angler-userdebug
add_lunch_combo xenonhd_endeavoru-userdebug
add_lunch_combo xenonhd_grouper-userdebug
add_lunch_combo xenonhd_kenzo-userdebug
add_lunch_combo xenonhd_m7-userdebug
add_lunch_combo xenonhd_m8-userdebug
