PRODUCT_MAKEFILES := \
	$(LOCAL_DIR)/crespo.mk \
	$(LOCAL_DIR)/d2att.mk \
	$(LOCAL_DIR)/d2tmo.mk \
	$(LOCAL_DIR)/d2usc.mk \
	$(LOCAL_DIR)/d2vzw.mk \
	$(LOCAL_DIR)/e975.mk \
	$(LOCAL_DIR)/endeavoru.mk \
	$(LOCAL_DIR)/find5.mk \
	$(LOCAL_DIR)/flo.mk \
	$(LOCAL_DIR)/galaxysmtd.mk \
	$(LOCAL_DIR)/grouper.mk \
	$(LOCAL_DIR)/hammerhead.mk \
    $(LOCAL_DIR)/i605.mk \
	$(LOCAL_DIR)/i9100.mk \
    $(LOCAL_DIR)/i9100g.mk \
    $(LOCAL_DIR)/i9300.mk \
    $(LOCAL_DIR)/i9305.mk \
    $(LOCAL_DIR)/jflte.mk \
    $(LOCAL_DIR)/l900.mk \
    $(LOCAL_DIR)/maguro.mk \
	$(LOCAL_DIR)/mako.mk \
	$(LOCAL_DIR)/mb886.mk \
    $(LOCAL_DIR)/m7tmo.mk \
	$(LOCAL_DIR)/n7000.mk \
	$(LOCAL_DIR)/n7100.mk \
    $(LOCAL_DIR)/r950.mk \
	$(LOCAL_DIR)/t0lte.mk \
	$(LOCAL_DIR)/t0lteatt.mk \
	$(LOCAL_DIR)/t0ltetmo.mk \
	$(LOCAL_DIR)/tilapia.mk \
	$(LOCAL_DIR)/toro.mk \
	$(LOCAL_DIR)/toroplus.mk \
	$(LOCAL_DIR)/vigor.mk \
	$(LOCAL_DIR)/xt925.mk \
	$(LOCAL_DIR)/xt926.mk \
    $(LOCAL_DIR)/xt907.mk
