PRODUCT_MAKEFILES := \
        $(LOCAL_DIR)/xenonhd_bacon.mk \
        $(LOCAL_DIR)/xenonhd_baconcaf.mk \
	$(LOCAL_DIR)/xenonhd_crespo.mk \
	$(LOCAL_DIR)/xenonhd_cancro.mk \
	$(LOCAL_DIR)/xenonhd_d2spr.mk \
	$(LOCAL_DIR)/xenonhd_d2bst.mk \
	$(LOCAL_DIR)/xenonhd_d2att.mk \
 	$(LOCAL_DIR)/xenonhd_d2tmo.mk \
 	$(LOCAL_DIR)/xenonhd_d2usc.mk \
 	$(LOCAL_DIR)/xenonhd_d2vzw.mk \
 	$(LOCAL_DIR)/xenonhd_d850.mk \
 	$(LOCAL_DIR)/xenonhd_d851.mk \
 	$(LOCAL_DIR)/xenonhd_d852.mk \
 	$(LOCAL_DIR)/xenonhd_d855.mk \
	$(LOCAL_DIR)/xenonhd_e975.mk \
	$(LOCAL_DIR)/xenonhd_endeavoru.mk \
	$(LOCAL_DIR)/xenonhd_f400.mk \
	$(LOCAL_DIR)/xenonhd_falcon.mk \
	$(LOCAL_DIR)/xenonhd_find5.mk \
	$(LOCAL_DIR)/xenonhd_find7.mk \
	$(LOCAL_DIR)/xenonhd_flo.mk \
	$(LOCAL_DIR)/xenonhd_galaxysmtd.mk \
	$(LOCAL_DIR)/xenonhd_geehrc.mk \
	$(LOCAL_DIR)/xenonhd_ghost.mk \
	$(LOCAL_DIR)/xenonhd_grouper.mk \
	$(LOCAL_DIR)/xenonhd_h345.mk \
	$(LOCAL_DIR)/xenonhd_hammerhead.mk \
	$(LOCAL_DIR)/xenonhd_hammerheadcaf.mk \
	$(LOCAL_DIR)/xenonhd_honami.mk \
	$(LOCAL_DIR)/xenonhd_i605.mk \
	$(LOCAL_DIR)/xenonhd_i9100.mk \
	$(LOCAL_DIR)/xenonhd_i9100g.mk \
	$(LOCAL_DIR)/xenonhd_i9300.mk \
	$(LOCAL_DIR)/xenonhd_i9305.mk \
	$(LOCAL_DIR)/xenonhd_jflte.mk \
	$(LOCAL_DIR)/xenonhd_jfltetmo.mk \
        $(LOCAL_DIR)/xenonhd_klte.mk \
	$(LOCAL_DIR)/xenonhd_l900.mk \
	$(LOCAL_DIR)/xenonhd_ls990.mk \
	$(LOCAL_DIR)/xenonhd_m7.mk \
	$(LOCAL_DIR)/xenonhd_m8.mk \
	$(LOCAL_DIR)/xenonhd_maguro.mk \
	$(LOCAL_DIR)/xenonhd_mako.mk \
	$(LOCAL_DIR)/xenonhd_mb886.mk \
	$(LOCAL_DIR)/xenonhd_m7tmo.mk \
	$(LOCAL_DIR)/xenonhd_nicki.mk \
	$(LOCAL_DIR)/xenonhd_n7000.mk \
	$(LOCAL_DIR)/xenonhd_n7100.mk \
	$(LOCAL_DIR)/xenonhd_r950.mk \
	$(LOCAL_DIR)/xenonhd_shamu.mk \
        $(LOCAL_DIR)/xenonhd_surnia.mk \
	$(LOCAL_DIR)/xenonhd_t0lte.mk \
	$(LOCAL_DIR)/xenonhd_t0lteatt.mk \
	$(LOCAL_DIR)/xenonhd_t0ltetmo.mk \
	$(LOCAL_DIR)/xenonhd_tilapia.mk \
	$(LOCAL_DIR)/xenonhd_toro.mk \
	$(LOCAL_DIR)/xenonhd_toroplus.mk \
	$(LOCAL_DIR)/xenonhd_trltetmo.mk \
        $(LOCAL_DIR)/xenonhd_trltespr.mk \
	$(LOCAL_DIR)/xenonhd_trltexx.mk \
        $(LOCAL_DIR)/xenonhd_victara.mk \
	$(LOCAL_DIR)/xenonhd_vigor.mk \
	$(LOCAL_DIR)/xenonhd_xt925.mk \
	$(LOCAL_DIR)/xenonhd_xt926.mk \
	$(LOCAL_DIR)/xenonhd_ville.mk \
	$(LOCAL_DIR)/xenonhd_xt907.mk \
	$(LOCAL_DIR)/xenonhd_vs985.mk
