#!/bin/bash
#
# Name the zip file and get md5
# XenonHD

. $ANDROID_BUILD_TOP/vendor/xenonhd/tools/colors

OUT_TARGET_HOST=`uname -a | grep Darwin`
if [ -z "$OUT_TARGET_HOST" ]
then
   MD5=md5sum
else
   MD5="md5 -r"
fi

# Determine what to name the new signed package
if [ -z "$XenonHD" ]; then
	MODVERSION=`sed -n -e'/ro\.xenonhd.version/s/^.*=//p' $OUT/system/build.prop`
	: ${MODVERSION:=}
        OTA_TYPE=`sed -n -e'/ro\.ota\.type/s/^.*=//p' $OUT/system/build.prop`
        : ${OTA_TYPE:=}
        DEVICE=`sed -n -e'/ro\.ota\.device/s/^.*=//p' $OUT/system/build.prop`
        : ${DEVICE:=}
	XENONHD_TARGET_PACKAGE=$MODVERSION-$DEVICE.zip
	OUTFILE=$OUT/$XENONHD_TARGET_PACKAGE
else
	XENONHD_TARGET_PACKAGE=xenonhd-squished.zip
	OUTFILE=$OUT/$XENONHD_TARGET_PACKAGE
fi

# Create OTA XML file
if [ -f $ANDROID_BUILD_TOP/ota_conf ]; then
cat >$OUT/ota_nougat_$DEVICE.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<XenonOTA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ota.xsd">
    <Stable>
        <$DEVICE>
            <Filename>$MODVERSION</Filename>
            <RomUrl
                id="rom"
                title="ROM"
                description="Download the latest build">https://mirrors.c0urier.net/android/teamhorizon/N/$OTA_TYPE/$DEVICE/$XENONHD_TARGET_PACKAGE</RomUrl>
            <MD5Url
                id="md5"
                title="MD5"
                description="Download MD5 of the latest build">https://mirrors.c0urier.net/android/teamhorizon/N/$OTA_TYPE/$DEVICE/$XENONHD_TARGET_PACKAGE.md5sum</MD5Url>
            <ChangelogUrl
                id="changelog"
                title="Changelog"
                description="View the latest changelog">https://mirrors.c0urier.net/android/teamhorizon/N/$OTA_TYPE/$DEVICE/Changelog.txt</ChangelogUrl>
            <OpenGappsUrl
                id="opengapps"
                title="Open Gapps"
                description="Download Open Gapps">http://opengapps.org</OpenGappsUrl>
        </$DEVICE>
    </Stable>
</XenonOTA>
EOF
fi

# Create a md5 checksum image of the repacked package
(
img=`basename $OUTFILE`
cd `dirname $OUTFILE`
ln -f *-ota-*.zip $XENONHD_TARGET_PACKAGE
rm *-ota-*.zip
$MD5 $img >$XENONHD_TARGET_PACKAGE.md5sum
ZIPSIZE=`ls -lah $OUTFILE | awk '{ print $5}' `
echo -e ${cya}"===========-Package complete-==========="${txtrst}
echo -e ${cya}"zip:"${cya}" $XENONHD_TARGET_PACKAGE"${txtrst}
echo -e ${cya}"md5:"${cya}" $(cat $XENONHD_TARGET_PACKAGE.md5sum | awk '{ print $1 }')"${txtrst}
echo -e ${cya}"size:"${cya}" $ZIPSIZE"${txtrst}
echo -e ${cya}"========================================"${txtrst}
)
