#!/bin/bash
#
# Name the zip file and get md5
# XenonHD

. $ANDROID_BUILD_TOP/vendor/xenonhd/tools/colors


OUT_TARGET_HOST=`uname -a | grep Darwin`
if [ -z "$OUT_TARGET_HOST" ]
then
   MD5=md5sum
else
   MD5="md5 -r "
fi

# Determine what to name the new signed package
if [ -z "$XenonHD" ]; then
	MODVERSION=`sed -n -e'/ro\.xehdversion/s/^.*=//p' $OUT/system/build.prop`
	: ${MODVERSION:=}
        Device=`sed -n -e'/ro\.ota\.device/s/^.*=//p' $OUT/system/build.prop`
        : ${Device:=}
        OTA_TYPE=`sed -n -e'/ro\.ota\.type/s/^.*=//p' $OUT/system/build.prop`
        : ${OTA_TYPE:=}
        OTA_FILENAME=`sed -n -e'/ro\.ota\.version/s/^.*=//p' $OUT/system/build.prop`
        : ${OTA_FILENAME:=}
	XENONHD_TARGET_PACKAGE=update-$MODVERSION-signed-$Device.zip
	OUTFILE=$OUT/$XENONHD_TARGET_PACKAGE
else
	XENONHD_TARGET_PACKAGE=update-squished.zip
	OUTFILE=$OUT/$XENONHD_TARGET_PACKAGE
fi

# Create OTA XML file
if [ -f $ANDROID_BUILD_TOP/ota_conf ]; then
cat >$OUT/ota_marshmallow.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<SlimOTA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ota.xsd">
    <Stable>
        <$Device>
            <Filename>$OTA_FILENAME</Filename>
            <RomUrl
                id="rom"
                title="Rom"
                description="Download latest XenonHD build">https://mirrors.c0urier.net/android/teamhorizon/$OTA_TYPE/$Device/$XENONHD_TARGET_PACKAGE</RomUrl>
            <MD5Url
                id="md5"
                title="Md5"
                description="Download XenonHD build md5">https://mirrors.c0urier.net/android/teamhorizon/$OTA_TYPE/$Device/$XENONHD_TARGET_PACKAGE.md5sum</MD5Url>
            <DownloadsURL
                id="downloads"
                title="Downloads"
                description="XenonHD Downloads for all builds">https://mirrors.c0urier.net/?dir=android/teamhorizon</DownloadsURL>
            <OpenGappsUrl
                id="opengapps"
                title="Open Gapps"
                description="Open Gapps Downloads">http://opengapps.org</OpenGappsUrl>
        </$Device>
    </Stable>
</SlimOTA>
EOF
fi

# Create a md5 checksum image of the repacked package
(
img=`basename $OUTFILE`
cd `dirname $OUTFILE`
ln -f *-ota-*.zip $XENONHD_TARGET_PACKAGE
rm *-ota-*.zip
$MD5 $img >$XENONHD_TARGET_PACKAGE.md5sum
ZIPSIZE=`ls -lah $OUTFILE | awk '{ print $5}' `
echo -e ${cya}"===========-Package complete-==========="${txtrst}
echo -e ${cya}"zip:"${cya}" $XENONHD_TARGET_PACKAGE"${txtrst}
echo -e ${cya}"md5:"${cya}" $(cat $XENONHD_TARGET_PACKAGE.md5sum | awk '{ print $1 }')"${txtrst}
echo -e ${cya}"size:"${cya}" $ZIPSIZE"${txtrst}
echo -e ${cya}"========================================"${txtrst}
)
