#!/bin/bash
# XenonHD OTA

# Determine build properties
if [ -z "$XenonHD" ]; then
	MODVERSION=`sed -n -e'/ro\.xenonhd.version/s/^.*=//p' $OUT/system/build.prop`
	: ${MODVERSION:=}
        OTA_TYPE=`sed -n -e'/ro\.ota\.type/s/^.*=//p' $OUT/system/build.prop`
        : ${OTA_TYPE:=}
        DEVICE=`sed -n -e'/ro\.ota\.device/s/^.*=//p' $OUT/system/build.prop`
        : ${DEVICE:=}
	XENONHD_TARGET_PACKAGE=$MODVERSION-$DEVICE.zip
fi

# Create OTA XML file
if [ -f $ANDROID_BUILD_TOP/ota_conf ]; then
cat >$OUT/ota_$DEVICE.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<XenonOTA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ota.xsd">
    <Stable>
        <$DEVICE>
            <Filename>$MODVERSION</Filename>
            <RomUrl
                id="rom"
                title="ROM"
                description="Download the latest build">https://mirrors.c0urier.net/android/teamhorizon/O/$OTA_TYPE/$DEVICE/$XENONHD_TARGET_PACKAGE</RomUrl>
            <MD5Url
                id="md5"
                title="MD5"
                description="Download MD5 of the latest build">https://mirrors.c0urier.net/android/teamhorizon/O/$OTA_TYPE/$DEVICE/$XENONHD_TARGET_PACKAGE.md5sum</MD5Url>
            <ChangelogUrl
                id="changelog"
                title="Changelog"
                description="View the latest changelog">https://mirrors.c0urier.net/android/teamhorizon/O/$OTA_TYPE/$DEVICE/Changelog.txt</ChangelogUrl>
            <OpenGappsUrl
                id="opengapps"
                title="Open Gapps"
                description="Download Open Gapps">http://opengapps.org</OpenGappsUrl>
            <ExtrasUrl
                id="extras"
                title="Extras"
                description="Download Extras">https://download.lineageos.org/extras</ExtrasUrl>
        </$DEVICE>
    </Stable>
</XenonOTA>
EOF
fi
